version = 0.1
[default.deploy.parameters]
stack_name = "myrtle-server-app"
s3_bucket = "tosuri-sam-artifact"
s3_prefix = "myrtle-server"
region = "ap-northeast-1"
confirm_changeset = false
capabilities = "CAPABILITY_NAMED_IAM"
disable_rollback = false
image_repositories = []
